// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SepeteEkleCikarTest', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SepeteEkleCikarTest', async function() {
    await driver.get("https://www.testrelic.com/bugshop/")
    await driver.manage().window().setRect(1792, 1043)

    
    await driver.findElement(By.linkText("Women")).click()
    await driver.findElement(By.linkText("Brown body bag")).click()
    await driver.findElement(By.css(".widget_edd_product_details")).click()
    await driver.findElement(By.name("edd_download_quantity")).clear()
    await driver.findElement(By.name("edd_download_quantity")).sendKeys("2")
    await driver.findElement(By.css(".edd_purchase_submit_wrapper")).click()
    await driver.wait(until.elementLocated(By.linkText("Remove")), 8000)
    await driver.wait(until.elementTextIs(await driver.findElement(By.linkText("Remove")), 'Remove'), 8000)
    await driver.findElement(By.linkText("Remove")).click()
    await driver.findElement(By.id("edd_checkout_wrap")).click()
    assert(await driver.findElement(By.css(".edd_empty_cart")).getText() == "Your cart is empty.")
    await driver.sleep(3000)
  })
})
